<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDtyCR1Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDtyCR1Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDtyCR1Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDtyCR1Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDtyCR1Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'DtyCR1Y',
    'container.build_id' => '8a5b4117',
    'container.build_time' => 1739212567,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDtyCR1Y');
